package com.guvi.languageplatform.jdbc;

import org.springframework.stereotype.Repository;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** CRUD operations on the lessons table using plain JDBC (no JPA). */
@Repository
public class JdbcLessonDao {

    /** Small read-only holder for one lesson row (a Java record). */
    public record LessonRow(long id, String title, String language, String difficulty,
                            String status, String instructorEmail) { }

    private final DataSource dataSource;

    public JdbcLessonDao(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    /** CREATE: inserts one lesson. The id is generated by the database. */
    public int insert(String title, String language, String difficulty, String content,
                      String quizQuestion, String quizAnswer, String status,
                      String instructorEmail) throws SQLException {
        String sql = "INSERT INTO lessons (title, language, difficulty, content, "
                + "quiz_question, quiz_answer, status, instructor_email) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, title);
            ps.setString(2, language);
            ps.setString(3, difficulty);
            ps.setString(4, content);
            ps.setString(5, quizQuestion);
            ps.setString(6, quizAnswer);
            ps.setString(7, status);
            ps.setString(8, instructorEmail);
            return ps.executeUpdate();   // number of rows inserted
        }
    }

    /** READ: all lessons with the given status (PENDING, APPROVED or REJECTED). */
    public List<LessonRow> findByStatus(String status) throws SQLException {
        String sql = "SELECT id, title, language, difficulty, status, instructor_email "
                + "FROM lessons WHERE status = ? ORDER BY id";
        List<LessonRow> rows = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, status);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    rows.add(new LessonRow(rs.getLong("id"), rs.getString("title"),
                            rs.getString("language"), rs.getString("difficulty"),
                            rs.getString("status"), rs.getString("instructor_email")));
                }
            }
        }
        return rows;
    }

    /** READ (aggregate): how many lessons exist per status. */
    public Map<String, Integer> countByStatus() throws SQLException {
        return countGrouped("status");
    }

    /** READ (aggregate): how many lessons exist per language. */
    public Map<String, Integer> countByLanguage() throws SQLException {
        return countGrouped("language");
    }

    /** UPDATE: changes the status of one lesson. Returns the number of rows changed. */
    public int updateStatus(long id, String status) throws SQLException {
        String sql = "UPDATE lessons SET status = ? WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, status);
            ps.setLong(2, id);
            return ps.executeUpdate();
        }
    }

    /** DELETE: removes one lesson. Returns the number of rows deleted. */
    public int delete(long id) throws SQLException {
        String sql = "DELETE FROM lessons WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setLong(1, id);
            return ps.executeUpdate();
        }
    }

    /** Shared helper for GROUP BY counts. Only two fixed column names are allowed. */
    private Map<String, Integer> countGrouped(String column) throws SQLException {
        if (!column.equals("status") && !column.equals("language")) {
            throw new IllegalArgumentException("Unknown column: " + column);
        }
        String sql = "SELECT " + column + ", COUNT(*) FROM lessons GROUP BY " + column + " ORDER BY " + column;
        Map<String, Integer> result = new LinkedHashMap<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                result.put(rs.getString(1), rs.getInt(2));
            }
        }
        return result;
    }
}